export const DI_TOKENS = Object.freeze({
  IAuthService: 'IAuthService',
  ITransactionRepository: 'ITransactionRepository',
  IWalletRepository: 'IWalletRepository',
  ITransactionService: 'ITransactionService',
  IVaultTransactionRepository: 'IVaultTransactionRepository',
  ILedgerTransactionService: 'ILedgerTransactionService',
  IWalletService: 'IWalletService',
  ICategoryRepository: 'ICategoryRepository',
  ICategoryService: 'ICategoryService',
  IPayeeRepository: 'IPayeeRepository',
  ILoanRepository: 'ILoanRepository',
  IBudgetRepository: 'IBudgetRepository',
  IGoalRepository: 'IGoalRepository',
  IGoalLogicService: 'IGoalLogicService',
  ISubscriptionRepository: 'ISubscriptionRepository',
  IActivityLogService: 'IActivityLogService',
  IAssetLoader: 'IAssetLoader',
  IExportService: 'IExportService',
  ISyncEngine: 'ISyncEngine',
  IDatabase: 'IDatabase',
  IPredictionService: 'IPredictionService',
  IVaultCryptoManager: 'IVaultCryptoManager',
  IAutoCreateService: 'IAutoCreateService',
  IAutoCategorizationService: 'IAutoCategorizationService',
  IDashboardService: 'IDashboardService',
  ILogger: 'ILogger',
} as const);
