"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __generator = (this && this.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g = Object.create((typeof Iterator === "function" ? Iterator : Object).prototype);
    return g.next = verb(0), g["throw"] = verb(1), g["return"] = verb(2), typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (g && (g = 0, op[0] && (_ = 0)), _) try {
            if (f = 1, y && (t = op[0] & 2 ? y["return"] : op[0] ? y["throw"] || ((t = y["return"]) && t.call(y), 0) : y.next) && !(t = t.call(y, op[1])).done) return t;
            if (y = 0, t) op = [op[0] & 2, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
    }
};
Object.defineProperty(exports, "__esModule", { value: true });
/// <reference lib="webworker" />
var workbox_precaching_1 = require("workbox-precaching");
var db_1 = require("./core/db");
(0, workbox_precaching_1.cleanupOutdatedCaches)();
// Precache all assets generated by Vite
(0, workbox_precaching_1.precacheAndRoute)(self.__WB_MANIFEST);
// Logic for generating transactions from subscriptions
function processSubscriptions() {
    return __awaiter(this, void 0, void 0, function () {
        var subscriptions, today, currentDay, _i, subscriptions_1, sub, lastBilled, alreadyBilled, error_1;
        return __generator(this, function (_a) {
            switch (_a.label) {
                case 0:
                    console.log('[SW] Checking for due subscriptions...');
                    _a.label = 1;
                case 1:
                    _a.trys.push([1, 8, , 9]);
                    return [4 /*yield*/, db_1.db.table('subscriptions').toArray()];
                case 2:
                    subscriptions = _a.sent();
                    today = new Date();
                    currentDay = today.getDate();
                    _i = 0, subscriptions_1 = subscriptions;
                    _a.label = 3;
                case 3:
                    if (!(_i < subscriptions_1.length)) return [3 /*break*/, 7];
                    sub = subscriptions_1[_i];
                    if (!(sub.billing_day <= currentDay)) return [3 /*break*/, 6];
                    lastBilled = sub.last_billed_at ? new Date(sub.last_billed_at) : null;
                    alreadyBilled = lastBilled &&
                        lastBilled.getMonth() === today.getMonth() &&
                        lastBilled.getFullYear() === today.getFullYear();
                    if (!!alreadyBilled) return [3 /*break*/, 6];
                    console.log("[SW] Billing subscription: ".concat(sub.name));
                    // Create transaction
                    return [4 /*yield*/, db_1.db.table('transactions').add({
                            id: crypto.randomUUID(),
                            title: "Assinatura: ".concat(sub.name),
                            amount: -sub.amount,
                            type: 'expense',
                            category_id: sub.category_id,
                            wallet_id: sub.wallet_id,
                            date: today.toISOString(),
                            synced: false,
                            deleted: false,
                            updated_at: today.toISOString(),
                        })
                        // Update subscription last billed date
                    ];
                case 4:
                    // Create transaction
                    _a.sent();
                    // Update subscription last billed date
                    return [4 /*yield*/, db_1.db.table('subscriptions').update(sub.id, {
                            last_billed_at: today.toISOString(),
                            synced: false,
                        })];
                case 5:
                    // Update subscription last billed date
                    _a.sent();
                    _a.label = 6;
                case 6:
                    _i++;
                    return [3 /*break*/, 3];
                case 7: return [3 /*break*/, 9];
                case 8:
                    error_1 = _a.sent();
                    console.error('[SW] Error processing subscriptions:', error_1);
                    return [3 /*break*/, 9];
                case 9: return [2 /*return*/];
            }
        });
    });
}
// Custom logic for offline sync and background updates
self.addEventListener('message', function (event) {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
    if (event.data && event.data.type === 'CHECK_SUBSCRIPTIONS') {
        processSubscriptions();
    }
});
// Trigger check on install/activate or periodically if supported
self.addEventListener('activate', function () {
    processSubscriptions();
});
console.log('Divi Service Worker Initialized.');
