/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching'
import { db } from './core/db'

declare let self: ServiceWorkerGlobalScope

cleanupOutdatedCaches()

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST)

// 1. App Shell Strategy: Serve index.html for all navigation requests (SPA)
import { registerRoute, NavigationRoute } from 'workbox-routing'
import { createHandlerBoundToURL } from 'workbox-precaching'
import { CacheFirst, StaleWhileRevalidate, NetworkFirst } from 'workbox-strategies'
import { ExpirationPlugin } from 'workbox-expiration'

if (import.meta.env.PROD) {
  try {
    const handler = createHandlerBoundToURL('/index.html')
    const navigationRoute = new NavigationRoute(handler)
    registerRoute(navigationRoute)
  } catch (e) {
    console.warn('[SW] Navigation cache failure, falling back to network dynamic routing', e)
  }
} else {
  // In development, we don't precache everything, so we use a simpler strategy for navigation
  registerRoute(
    ({ request }) => request.mode === 'navigate',
    new NetworkFirst({
      cacheName: 'dev-navigation',
    })
  )
}

// 2. Runtime Caching: Google Fonts e Assets Externos
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com' || url.origin === 'https://fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'google-fonts',
    plugins: [
      new ExpirationPlugin({ maxEntries: 20, maxAgeSeconds: 60 * 60 * 24 * 365 }) // 1 ano
    ]
  })
)

// 3. Cache de imagens (Avatares, etc)
registerRoute(
  ({ request }) => request.destination === 'image',
  new StaleWhileRevalidate({
    cacheName: 'images',
    plugins: [
      new ExpirationPlugin({ maxEntries: 50, maxAgeSeconds: 60 * 60 * 24 * 30 }) // 30 dias
    ]
  })
)

// Logic for generating transactions from subscriptions
async function processSubscriptions() {
  console.log('[SW] Checking for due subscriptions...')
  try {
    const subscriptions = await db.table('subscriptions').toArray()
    const today = new Date()
    const currentDay = today.getDate()

    for (const sub of subscriptions) {
      if (sub.billing_day <= currentDay) {
        // Check if already billed this month
        const lastBilled = sub.last_billed_at ? new Date(sub.last_billed_at) : null
        const alreadyBilled =
          lastBilled &&
          lastBilled.getMonth() === today.getMonth() &&
          lastBilled.getFullYear() === today.getFullYear()

        if (!alreadyBilled) {
          console.log(`[SW] Billing subscription: ${sub.name}`)

          // Create transaction
          await db.table('transactions').add({
            id: crypto.randomUUID(),
            title: `Assinatura: ${sub.name}`,
            amount: -sub.amount,
            type: 'expense',
            category_id: sub.category_id,
            wallet_id: sub.wallet_id,
            date: today.toISOString(),
            syncStatus: 'pending',
            deleted: false,
            updated_at: today.toISOString(),
          })

          // Update subscription last billed date
          await db.table('subscriptions').update(sub.id, {
            last_billed_at: today.toISOString(),
            syncStatus: 'pending',
          })
        }
      }
    }
  } catch (error) {
    if ((error as any).name === 'InvalidStateError' || (error as any).message?.includes('closing')) {
      console.warn('[SW] Database connection is closing or closed during subscription processing. Scaling back.')
    } else {
      console.error('[SW] Error processing subscriptions:', error)
    }
  }
}

// Custom logic for offline sync and background updates
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting()
  }

  if (event.data && event.data.type === 'CHECK_SUBSCRIPTIONS') {
    event.waitUntil(processSubscriptions())
  }
})

// Trigger check on install/activate or periodically if supported
self.addEventListener('activate', (event) => {
  event.waitUntil(processSubscriptions())
})

console.log('Divi Service Worker Initialized.')

