/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching'
import { db } from './core/db'

declare let self: ServiceWorkerGlobalScope

cleanupOutdatedCaches()

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST)

// Logic for generating transactions from subscriptions
async function processSubscriptions() {
  console.log('[SW] Checking for due subscriptions...')
  try {
    const subscriptions = await db.table('subscriptions').toArray()
    const today = new Date()
    const currentDay = today.getDate()

    for (const sub of subscriptions) {
      if (sub.billing_day <= currentDay) {
        // Check if already billed this month
        const lastBilled = sub.last_billed_at ? new Date(sub.last_billed_at) : null
        const alreadyBilled = lastBilled && 
          (lastBilled.getMonth() === today.getMonth() && lastBilled.getFullYear() === today.getFullYear())

        if (!alreadyBilled) {
          console.log(`[SW] Billing subscription: ${sub.name}`)
          
          // Create transaction
          await db.table('transactions').add({
            id: crypto.randomUUID(),
            title: `Assinatura: ${sub.name}`,
            amount: -sub.amount,
            type: 'expense',
            category_id: sub.category_id,
            wallet_id: sub.wallet_id,
            date: today.toISOString(),
            synced: false,
            deleted: false,
            updated_at: today.toISOString()
          })

          // Update subscription last billed date
          await db.table('subscriptions').update(sub.id, {
            last_billed_at: today.toISOString(),
            synced: false
          })
        }
      }
    }
  } catch (error) {
    console.error('[SW] Error processing subscriptions:', error)
  }
}

// Custom logic for offline sync and background updates
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting()
  }
  
  if (event.data && event.data.type === 'CHECK_SUBSCRIPTIONS') {
    processSubscriptions()
  }
})

// Trigger check on install/activate or periodically if supported
self.addEventListener('activate', () => {
  processSubscriptions()
})

console.log('Divi Service Worker Initialized.')
