/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching'

declare let self: ServiceWorkerGlobalScope

cleanupOutdatedCaches()

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST)

// 1. App Shell Strategy: Serve index.html for all navigation requests (SPA)
import { registerRoute, NavigationRoute } from 'workbox-routing'
import { createHandlerBoundToURL } from 'workbox-precaching'
import { CacheFirst, StaleWhileRevalidate, NetworkFirst } from 'workbox-strategies'
import { ExpirationPlugin } from 'workbox-expiration'

if (import.meta.env.PROD) {
  try {
    const handler = createHandlerBoundToURL('/index.html')
    const navigationRoute = new NavigationRoute(handler)
    registerRoute(navigationRoute)
  } catch (e) {
    console.warn('[SW] Navigation cache failure, falling back to network dynamic routing', e)
  }
} else {
  // In development, we don't precache everything, so we use a simpler strategy for navigation
  registerRoute(
    ({ request }) => request.mode === 'navigate',
    new NetworkFirst({
      cacheName: 'dev-navigation',
    }),
  )
}

// 2. Runtime Caching: Google Fonts e Assets Externos
registerRoute(
  ({ url }) =>
    url.origin === 'https://fonts.googleapis.com' || url.origin === 'https://fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'google-fonts',
    plugins: [
      new ExpirationPlugin({ maxEntries: 20, maxAgeSeconds: 60 * 60 * 24 * 365 }), // 1 ano
    ],
  }),
)

// 3. Cache de imagens (Avatares, etc)
registerRoute(
  ({ request }) => request.destination === 'image',
  new StaleWhileRevalidate({
    cacheName: 'images',
    plugins: [
      new ExpirationPlugin({ maxEntries: 50, maxAgeSeconds: 60 * 60 * 24 * 30 }), // 30 dias
    ],
  }),
)

// Custom logic for offline sync and background updates
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting()
  }
})

console.log('Divi Service Worker Initialized.')
